<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('36', '/uploads/userup/16/1605000191-1403.jpg');
$maNum = 1;
$myaddons[$maNum] = array('0', '/uploads/userup/16/1605000191-1403.jpg');
$maNum = 2;
$myaddons[$maNum] = array('0', '/uploads/userup/16/1605000191-1403.jpg');
$maNum = 3;
$myaddons[$maNum] = array('0', '/uploads/userup/16/1605000191-1403.jpg');
$maNum = 4;
$myaddons[$maNum] = array('0', '/uploads/userup/16/1605000191-1403.jpg');
$maNum = 4;
$myaddons[$maNum] = array('0', '/uploads/userup/16/1605000191-1403.jpg');
$maNum = 4;
