<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('37', '/uploads/userup/17/160KVC7-2393.jpg');
$maNum = 1;
$myaddons[$maNum] = array('0', '/uploads/userup/17/160KVC7-2393.jpg');
$maNum = 2;
$myaddons[$maNum] = array('0', '/uploads/userup/17/160KVC7-2393.jpg');
$maNum = 3;
$myaddons[$maNum] = array('0', '/uploads/userup/17/160KVC7-2393.jpg');
$maNum = 4;
$myaddons[$maNum] = array('0', '/uploads/userup/17/160KVC7-2393.jpg');
$maNum = 5;
$myaddons[$maNum] = array('0', '/uploads/userup/17/160KVC7-2393.jpg');
$maNum = 6;
