<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('33', '/uploads/userup/6/1600954349-E54.jpg');
$maNum = 1;
$myaddons[$maNum] = array('34', '/uploads/userup/6/1600954350-W29.jpg');
$maNum = 2;
$myaddons[$maNum] = array('0', '/uploads/userup/3/1600939510-RH.jpg');
$maNum = 3;
$myaddons[$maNum] = array('0', '/uploads/userup/3/16009392X-4L2.jpg');
$maNum = 4;
$myaddons[$maNum] = array('0', '/uploads/userup/3/1600939510-RH.jpg');
$maNum = 5;
$myaddons[$maNum] = array('0', '/uploads/userup/3/16009392X-4L2.jpg');
$maNum = 6;
