<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '产品展示';
$typeArr[3] = '产品一类';
$typeArr[4] = '产品二类';
$typeArr[5] = '产品三类';
$typeArr[6] = '产品四类';
$typeArr[7] = '荣誉资质';
$typeArr[13] = '新闻资讯';
$typeArr[9] = '成功案例';
$typeArr[11] = '厂区展示';
$typeArr[12] = '联系我们';
$typeArr[14] = '首页幻灯';
$typeArr[16] = '公司新闻';
$typeArr[17] = '行业新闻';
$typeArr[22] = '企业简介';
$typeArr[23] = '企业资质';
$typeArr[24] = '企业理念';
$typeArr[25] = '企业文化';
$typeArr[27] = '媒体报道';
?>