<?php
$z[0]=Array("field","",219,238);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",239,265);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",309,339);
$z[2][4]=array();
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",376,403);
$z[3][4]=array();
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",1147,1186);
$z[4][4]=array();
$z[4][4]['filename']="header_m.htm";
$z[5]=Array("field","",1483,1512);
$z[5][4]=array();
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\"></span></li>\r\n        ",1737,2065);
$z[6][4]=array();
$z[6][4]['type']="son";
$z[6][4]['row']="10";
$z[6][4]['currentstyle']="<li class='hover'><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[7]=Array("field","",2215,2234);
$z[7][4]=array();
$z[7][4]['name']="title";
$z[8]=Array("field","",2283,2301);
$z[8][4]=array();
$z[8][4]['name']="body";
$z[9]=Array("type"," <a href=\"list.php?tid=[field:id/]\" title=\"返回列表\" class=\"back\">返回列表</a>",2321,2430);
$z[9][4]=array();
$z[10]=Array("include","",2480,2519);
$z[10][4]=array();
$z[10][4]['filename']="footer_m.htm";

?>