<?php
$z[0]=Array("arclist","<li><a href=\"view.php?aid=[field:id/]\">[field:title/]</a></li> ",179,331);
$z[0][4]=array();
$z[0][4]['flag']="c";
$z[0][4]['typeid']="3";
$z[0][4]['row']="5";
$z[0][4]['titlelen']="50";
$z[0][4]['orderby']="pubdate";
$z[1]=Array("global","",582,604);
$z[1][4]=array();
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",606,628);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",695,718);
$z[3][4]=array();
$z[3][4]['name']="cfg_mail";
$z[4]=Array("global","",720,743);
$z[4][4]=array();
$z[4][4]['name']="cfg_mail";
$z[5]=Array("global","",791,813);
$z[5][4]=array();
$z[5][4]['name']="cfg_add";
$z[6]=Array("global","",1304,1326);
$z[6][4]=array();
$z[6][4]['name']="cfg_tel";

?>