<?php
$z[0]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]</a> ",278,368);
$z[0][4]=array();
$z[0][4]['type']="top";
$z[1]=Array("global","",414,440);
$z[1][4]=array();
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",442,466);
$z[2][4]=array();
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",491,513);
$z[3][4]=array();
$z[3][4]['name']="cfg_add";
$z[4]=Array("global","",523,545);
$z[4][4]=array();
$z[4][4]['name']="cfg_tel";
$z[5]=Array("global","",555,579);
$z[5][4]=array();
$z[5][4]['name']="cfg_phone";
$z[6]=Array("flink","\r\n            <li>[field:link /]</li>\r\n            ",834,945);
$z[6][4]=array();
$z[6][4]['titlelen']="20";
$z[6][4]['row']="20";
$z[6][4]['type']="text";

?>