<?php
$z[0]=Array("type"," <a href=\"[field:typelink/]\">[field:typename/]</a>",161,245);
$z[0][4]=array();
$z[0][4]['typeid']="1";
$z[1]=Array("type"," <a href=\"[field:typelink/]\">[field:typename/]</a>",246,331);
$z[1][4]=array();
$z[1][4]['typeid']="12";
$z[2]=Array("global","",388,410);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        ",551,766);
$z[3][4]=array();
$z[3][4]['type']="top";
$z[3][4]['currentstyle']="<li><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[4]=Array("arclist","\r\n        <li data-background=\"[field:picname/]\" alt=\"[field:title/]\"></li>\r\n        ",906,1064);
$z[4][4]=array();
$z[4][4]['typeid']="14";
$z[4][4]['titlelen']="50";
$z[4][4]['orderby']="pubdate";

?>