<?php
$z[0]=Array("global","",152,179);
$z[0][4]=array();
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("channel","  <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\"><span>[field:typename/]</span></a></li> ",2304,2569);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[1][4]['currentstyle']="<li class='hover'><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";

?>