<?php
$z[0]=Array("global","",219,245);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",1057,1096);
$z[1][4]=array();
$z[1][4]['filename']="header_m.htm";
$z[2]=Array("field","",1393,1422);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\"></span></li>\r\n        ",1647,1975);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li class='hover'><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[4]=Array("field","",2145,2166);
$z[4][4]=array();
$z[4][4]['name']="content";
$z[5]=Array("include","",2221,2260);
$z[5][4]=array();
$z[5][4]['filename']="footer_m.htm";

?>