<?php
$z[0]=Array("field","",78,107);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("channel"," <li><a href=\"[field:typeurl/]\" class=\"co00757F\">[field:typename/]</a></li> ",204,414);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<li><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[2]=Array("arclist","<a href=\"[field:arcurl/]\">[field:title/]</a>",617,707);
$z[2][4]=array();
$z[2][4]['flag']="c";
$z[2][4]['row']="6";

?>