<?php
$z[0]=Array("field","",309,328);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",329,355);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",396,425);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",465,523);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",958,997);
$z[4][4]=array();
$z[4][4]['filename']="header_m.htm";
$z[5]=Array("field","",1411,1440);
$z[5][4]=array();
$z[5][4]['name']="position";
$z[6]=Array("channel"," <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\" class=\"isel\">[field:typename/]</a>",1624,1769);
$z[6][4]=array();
$z[6][4]['type']="son";
$z[6][4]['row']="10";
$z[7]=Array("list"," <li>\r\n                    <a href=\"view.php?aid=[field:id/]\">\r\n                        <em>[field:pubdate function=\"MyDate('y-m-d',@me)\"/]</em>[field:title/]</a>\r\n                </li>",2181,2404);
$z[7][4]=array();
$z[7][4]['pagesize']="12";
$z[8]=Array("include","",2544,2583);
$z[8][4]=array();
$z[8][4]['filename']="footer_m.htm";

?>