<?php
$z[0]=Array("global","",275,301);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",342,371);
$z[1][4]=array();
$z[1][4]['name']="keywords";
$z[2]=Array("field","",411,469);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",1112,1147);
$z[3][4]=array();
$z[3][4]['filename']="head.htm";
$z[4]=Array("global","",1253,1308);
$z[4][4]=array();
$z[4][4]['name']="keyword";
$z[4][4]['function']="RemoveXSS(@me)";
$z[5]=Array("include","",1371,1406);
$z[5][4]=array();
$z[5][4]['filename']="left.htm";
$z[6]=Array("list","\r\n          <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></li>\r\n          ",1517,1700);
$z[6][4]=array();
$z[7]=Array("include","",1761,1798);
$z[7][4]=array();
$z[7][4]['filename']="footer.htm";

?>